runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: sudo apt install firefox imagemagick optipng
      shell: bash
    - run: npm install
      shell: bash
    - run: pip install -r requirements.txt
      shell: bash
